services:
  web:
    build: .
    image: superspuma:prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.superspuma.rule=Host(`superspuma.paragu-ai.com`)"
      - "traefik.http.routers.superspuma.entrypoints=websecure"
      - "traefik.http.services.superspuma.loadbalancer.server.port=3000"
